#!/usr/bin/env bash
# Configures Nginx to run as nginx user and listen on port 8080
sed -i 's/^user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/listen 80/listen 8080/' /etc/nginx/sites-enabled/default
sed -i 's/listen \[::\]:80/listen [::]:8080/' /etc/nginx/sites-enabled/default
nginx -t && service nginx restart
