#!/usr/bin/env bash
# Configures Nginx to run as nginx user and listen on port 8080
sed -i 's/^user .*/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80/listen 8080/g' /etc/nginx/sites-enabled/default
sed -i 's/listen \[::\]:80/listen [::]:8080/g' /etc/nginx/sites-enabled/default
grep -q "user nginx" /etc/nginx/nginx.conf || echo "user nginx;" >> /etc/nginx/nginx.conf
service nginx stop
sleep 1
service nginx start
