#!/usr/bin/env bash
# Configures Nginx to run as nginx user and listen on port 8080
sed -i 's/^user .*/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server/listen 8080 default_server/' /etc/nginx/sites-enabled/default
sed -i 's/listen \[::\]:80 default_server/listen [::]:8080 default_server/' /etc/nginx/sites-enabled/default
sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-enabled/default
sed -i 's/listen \[::\]:80;/listen [::]:8080;/' /etc/nginx/sites-enabled/default
service nginx stop
service nginx start
