#!/usr/bin/env bash
# Configures ufw to block all incoming traffic except TCP ports 22, 80, and 443
sudo apt-get update -y
sudo apt-get install -y ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw --force enable
