#!/usr/bin/env bash
# Installs and configures HAProxy with round-robin load balancing
apt-get update -y
apt-get install -y haproxy
echo "ENABLED=1" >> /etc/default/haproxy
cat > /etc/haproxy/haproxy.cfg << 'HAPROXY'
global
    log /dev/log local0
    maxconn 2048
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 7084-web-01 13.218.52.231:80 check
    server 7084-web-02 3.87.7.134:80 check
HAPROXY
service haproxy restart
