#!/usr/bin/env bash
# Fixes Nginx to listen on port 80
rm -f /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
nginx -g 'daemon off;' &
service nginx start
